version: '2'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    entrypoint: make
    command: test
    links:
      - db:db
    volumes:
      - ".:/go/src/github.com/remind101/empire"
    environment:
      TEST_DATABASE_URL: "postgres://postgres:postgres@db/postgres?sslmode=disable"
  db:
    # Postgres 9
    image: postgres@sha256:9aa0b86ae3be8de6f922441b913e8914e840c652b6880a642f42f98f5e2aaeaf
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

